FROM node:18-alpine3.16 AS build-stage

WORKDIR /tmp

COPY package*.json /tmp

RUN npm i

COPY . /tmp

ENV REACT_APP_BACKEND_BASE_URL=http://167.71.185.132:3001/api

RUN npm run build

FROM nginx:1.12-alpine AS production-stage

COPY --from=build-stage /tmp/build /usr/share/nginx/html

ENTRYPOINT nginx -g 'daemon off;'

