# docker-compose.yml - defining docker containers

# Our entire containers: 
services:

  # Our database service: 
  vacations-database-service: 

    # Database image: 
    image: vacations-database-image

    # Where is the Dockerfile to create image from:
    build: ./Database

    # Container name: 
    container_name: vacations-database-container

    # Port Bindings: 
    ports:
      - 3306:3306

    # Environment Variables: 
    environment:
      MARIADB_HOST: localhost # internal to the container
      MARIADB_DATABASE: vacations
      MARIADB_ROOT_USER: Tomer
      MARIADB_ROOT_PASSWORD: Viner

    # Container restart policy:
    restart: unless-stopped

    # Named Volume to persist the database:
    volumes: 
      # - vacations:/var/lib/mysql
      - vacations:/bitnami/mariadb


# ------------------------------------------------

  # Our backend container:
  vacations-backend-service: 

    # Image name to create:
    image: vacations-backend-image

    # Where is the Dockerfile to create image from:
    build: ./Backend

    # What is the name of the container to create: 
    container_name: vacations-backend-container

    # Port Binding (host:container):
    ports:
      - 3001:3001

    # Environment Variables: 
    environment:
      MYSQL_HOST: vacations-database-service # Service name is the host name - where the database exists.
      MYSQL_DATABASE: vacations
      MYSQL_USER: Tomer
      MYSQL_PASSWORD: Viner

    # Container restart policy:
    restart: unless-stopped

    # Volumes between container to host:
    volumes:
      # Host Volume for Hot-Reloading:
      - ./Backend:/app

    # Which service we're depending on (for boot sequence):
    depends_on:
      - vacations-database-service

# ------------------------------------------------

  # Frontend container: 
  vacations-frontend-service: 

    # Image name: 
    image: vacations-frontend-image

    # Where the Dockerfile exists: 
    build: ./Frontend

    # Container name: 
    container_name: vacations-frontend-container

    # Port binding (host:container): 
    ports: 
      - 3000:3000

    # Restart policy: 
    restart: unless-stopped

    # Host Volume (for hot reloading): 
    volumes: 
      - ./Frontend:/app

    # Which project we're depending on:
    depends_on:
      - vacations-backend-service

# ------------------------------------------------

# Named Volume list for recognizing all named volumes:
volumes:
  vacations:

